export class Character{
    name:string;
    damageModifier:number;
}
export const Heroes :string[]= ["Superman",
"Batman",
"Spider-Man",
"Wolverine",
"Wonder Woman",
"Captain America",
"Hal Jordan",
"Wally West",
"Hulk",
"Daredevil",
"Dick Grayson",
"Iron Man",
"Jean Grey",
"Thor",
"Dream of the Endless (Morpheus)",
"Rorschach",
"Barbara Gordon",
"Thing",
"James Gordon",
"Catwoman",
"The Spirit",
"Professor X",
"Raphael",
"Yorick Brown",
"Hellboy",
"Rick Grimes",
"Punisher",
"Swamp Thing",
"John Constantine",
"Green Arrow",
"Deadpool",
"Tim Drake",
"Nick Fury",
"Jesse Custer",
"Judge Dredd",
"Spawn (Simmons)",
"The Crow",
"Doctor Strange",
"Cyclops",
"Mr. Fantastic",
"Silver Surfer",
"Storm",
"Martian Manhunter",
"Hawkeye",
"Spider Jerusalem",
"Human Torch",
"Kitty Pryde",
"Mitchell Hundred",
"Barry Allen",
"Billy Batson",
"Black Panther",
"Aquaman",
"Bucky Barnes",
"Elijah Snow",
"John Stewart",
"Hawkman",
"The Tick",
"Beast",
"Booster Gold",
"Fone Bone",
"Blue Beetle (Reyes)",
"Dashiell Bad Horse",
"Blade",
"Ray Palmer",
"Gambit",
"Invisible Woman",
"Hank Pym",
"Iron Fist",
"Scott Pilgrim",
"Spectre",
"Wildcat",
"Luke Cage",
"Jonah Hex",
"Black Widow",
"Marv",
"The Rocketeer",
"Namor",
"Sgt. Rock",
"Captain Britain",
"Nightcrawler",
"Black Canary",
"Eric O'Grady",
"Kon-El",
"Ka-Zar",
"Black Lightning",
"Michonne",
"Renee Montoya",
"She-Hulk",
"Moon Knight",
"Ghost Rider (Blaze)",
"Cerebus",
"Usagi Yojimbo",
"Donna Troy",
"Supergirl",
"Savage Dragon",
"Falcon",
"Adam Strange",
"Nova",
"Wasp",
"Groo" 
]
export const Villains:string[] = ["Doctor Doom",
"Magneto",
"Norman Osborn",
"Red Skull",
"Loki",
"Galactus",
"Ultron",
"Thanos",
"Apocalypse",
"Kingpin",
"Doctor Octopus",
"Venom",
"Kang",
"Mephisto",
"Dormammu",
"Mandarin",
"Leader",
"Baron Helmut Zemo",
"Sabretooth",
"Carnage",
"Phoenix Force",
"Bullseye",
"Mystique",
"Abomination",
"M.O.D.O.K.",
"Annihilus",
"Juggernaut",
"Thunderbolt Ross",
"Super-Skrull",
"Mr. Sinister",
"Baron von Strucker",
"Onslaught",
"Immortus",
"Sentinels",
"Viper",
"Klaw",
"Wizard",
"Morgan Le Fay",
"Grandmaster",
"Magus",
"The Hood",
"Doctor Faustus",
"Sebastian Shaw",
"Enchantress",
"Ronan",
"High Evolutionary",
"Beyonder",
"Graviton",
"Maestro",
"Emma Frost",
"Arnim Zola",
"Justin Hammer",
"Baron Mordo",
"Surtur",
"Sentry",
"Kraven the Hunter",
"Crossbones",
"Count Nefaria",
"Taskmaster",
"Mad Thinker",
"Purple Man",
"Lady Deathstrike",
"Baron Heinrich Zemo",
"Lizard",
"Collector",
"Grim Reaper",
"U-Foes",
"Madame Masque",
"Vulcan",
"Ares",
"Nitro",
"Executioner",
"Hobgoblin (Kingsley)",
"Sin",
"Romulus",
"Mysterio",
"Korvac",
"William Stryker",
"Nuke",
"Proteus",
"Lilith",
"Stryfe",
"Lucia Von Bardas",
"Sandman",
"Cassandra Nova",
"Supreme Intelligence",
"Nimrod",
"Hela",
"Madelyne Pryor",
"Electro",
"Pluto",
"Red Ghost",
"Omega Red",
"Maximus",
"Callisto",
"Blackheart",
"Selene",
"Terrax",
"Tiger Shark",
"J. Jonah Jameson" 
]